"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []

# Nginx terminates TLS and proxies to Django over plain HTTP, so Django must
# trust the X-Forwarded-Proto header to know the original request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'fm_generator',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(os.environ['DATABASE_URL']),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media (uploaded user files, U1 of object-visuals)
# https://docs.djangoproject.com/en/5.2/ref/settings/#media-root
#
# docker-compose already mounts ./volumes/media at /app/media (== BASE_DIR /
# 'media' inside the container), so default FileSystemStorage lands uploads
# on the pre-provisioned volume. Deliberately NO MEDIA_URL-based public
# serving: variant files stream through an authenticated, owner-scoped API
# view (U3) — a public /media/ path would bypass ownership entirely.

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/
# Console backend for local dev — prints outgoing mail to stdout instead of
# actually sending it. Swap via env var once a real SMTP/provider backend
# is wired up for a non-local environment.

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@floorcraft.local')

# Used to build absolute links (e.g. email verification URLs) outside of a
# request/response cycle.
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')


# Session / CSRF cookie hardening (U3)
# https://docs.djangoproject.com/en/5.2/ref/settings/#session-cookie-samesite
#
# Safe given the stack is genuinely same-origin via Nginx in both dev and
# prod (see plan's Key Technical Decisions) — "Strict" would otherwise
# break any legitimate cross-site navigation into an authenticated page.
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Strict'

# The session cookie is never read by JS — httpOnly is a pure win.
SESSION_COOKIE_HTTPONLY = True

# The CSRF cookie MUST stay JS-readable: axios's `xsrfCookieName`/
# `xsrfHeaderName` config reads this cookie client-side and echoes it back
# as a request header (the "double submit cookie" pattern) — flipping this
# to `True` would silently break every unsafe (POST/PATCH/DELETE) request.
CSRF_COOKIE_HTTPONLY = False

# No cost given `SECURE_PROXY_SSL_HEADER` is already wired for the
# Nginx-TLS-termination topology above — prevents cookies from ever being
# sent over a plaintext channel if TLS termination is ever misconfigured.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Django REST Framework (U4)
# Session-authenticated and locked down by default; individual views opt
# into anonymous access explicitly (see accounts.views) rather than the
# other way around.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
