# Generated by Django 5.2.16 on 2026-07-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grid_size', models.PositiveIntegerField(default=20)),
                ('canvas_width', models.PositiveIntegerField(default=1600)),
                ('canvas_height', models.PositiveIntegerField(default=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('desk', 'Desk'), ('wall', 'Wall'), ('ac_unit', 'AC Unit'), ('light', 'Lighting Node')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField(default=40)),
                ('height', models.FloatField(default=40)),
                ('rotation', models.FloatField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fm_generator.floorplan')),
            ],
        ),
    ]
